---
title: "Research and Related Work"
---
***
<br>

## Selecting native plants to improve urban pollinator habitat
As a PhD Candidate at Oregon State University, I am studying the attractiveness of native wildflowers to pollinators and natural enemies, especially flowers with aesthetic value. This information has the potential to inform deliberate plantings that increase the habitat value of home gardens, urban parks, roadsides, and agricultural landscapes. This fits into my advisor Dr. Gail Langellotto's ongoing work in garden ecology. More information on our lab's on-goings can be found here:   http://blogs.oregonstate.edu/gardenecologylab/

Pollinator conservation is currently a hot-button issue in entomology, as well as among agricultural producers and savvy consumers. Because of this, interest in pollinator-friendly plantings has also increased. Unfortunately, if you are a home gardener or land manager interested in pollinator conservation, it is not always obvious what to plant. leading to a plethora of suggested pollinator planting lists geared towards home gardeners. Most of these lists are not based on empirical research, and in fact a 2014 study (Garbuzov and Ratnieks) found major issues with most of these published lists. 

To address this question in the Pacific Northwest, from 2017-2019 I ran a large field trial at OSU's North Willamette Research Center. I selected 23 native Willamette Valley wildflower species based on drought tolerance and aesthetic appeal, as well as four exotic garden species known to be attractive to bees for comparison. These flowers were all screened for their attractiveness to pollinators and other insect guilds. Throughout the field season I performed timed pollinator counts to assess pollinator abundance, and using an insect vaccuum sampled the insect communites (pollinators, natural enemies, and pests) present on each plant species. These data will be used to inform targeted pollinator habitat plantings in urban landscapes, and potentially in agricultural systems.

<br>

## Constructing a database of biocontrol agents released against insect pests
The United States has a long history of utilizing classical biological control against exotic insect pests. In fact, the first ever biological control effort was implemented in California from 1877-1879 against the cottony cushion scale (*Icerya purchasi*). The release of two foreign natural enemies resulted in the near elimination of this pest in California citrus, and was considered an incredible economic success. Over the subsequent years, more and more natural enemies were imported in mass quantities to combat exotic pests that global trade and travel introduced. However, the United States has lacked a cohesive record keeping system of natural enemy introductions that target insect pests. Releases against weeds have been much better documented, likely due to heightened concerns over non-target impacts (in partular fears that agents might consme crop plants). Because of this, summary information on classical biological control programs is correspondingly deficient.  
At Colorado State University, I constructed a databse of biocontrol agents released against insect pests in the United States, with the goal of producing a resource that contains information incuding species names, target hosts, soure location, release location, and any information on establishment and effiacy. This information will hopefully be useful to researchers and practitioners in the field going forward.

<br>

## Biocontrol of invasive insects via entomopathogens
Invasive forest pests can cause major ecological and economic damage when uncontrolled. The emerald ash borer is a perfect, if grim, exmaple. The question that faces entomologists and foresters is: how to control these pests effectively without non-target effects on native insects? A classic example of this is the indescriminate release of the parasitoid fly, *Compsilura concinnata* throughout the 1900s to combat several pest species. This fly was unfortunately a generalist, and it resulted in the precipitous decline of many native Saturniid moth species. 

Working in Dr. Ann Hajek's lab, I assisted studies on biological control of the Asian longorned beetle (*Anoplophora glabripennis*) and Sirex woodwasp (*Sirex noctilio*). Much of my work on the ALB involved quarantine lab trials testing the efficacy of different formulations of fungal bands - felt bands with spores entomopethogenic spores that would be transfered to beetles via contact. In the field, these bands are paird with chemical attractant lures (plant volatiles and a male beetle aggregation pheremone). I ran my own behavioral study to determine whether the ALB can detect the presence of the fungus used in these bands and avoid them. 

<br>

## Ecological restoration and outreach
I have worked doing habitat restoration, monitoring, and outreach for two different Federally Endangered butterflies - the Karner blue butterfly and Mission blue butterfly. Though their native ranges are on different sides of the country, both of these small blue Lycaenidae have similar life histories and are faced with similar threats to their habitats and obligate host plants (both utilize only certain lupine species), including altered fire regimes, invasive vegetation pressure, and habitat loss/fragmentation. 
<br>
  